[user]
email = "42196548+Sheeplet1@users.noreply.github.com"
name = "Anthony Do"

[git]
fetch = ["upstream", "origin"]
push = "origin"

[ui]
default-command = "log"

[aliases]
b = ["branch"]
n = ["new"]

# Move the closest bookmark to the current commit. This is useful when working
# on a named branch, creating a bunch of commits, and then needing to update
# the bookmark before pushing.
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]

# Rebase the current branch onto the trunk.
retrunk = ["rebase", "-d", "trunk"]

[revset-aliases]
"closest_bookmark(to)" = "heads(::to & bookmarks())"
"fork_history(to, from)" = "fork_point(to | from)..@"

[template-aliases]
"format_timestamp(timestamp)" =  "timestamp.ago()"
"in_branch(commit)" = 'commit.contained_in("immutable_heads()..bookmarks()")'

[templates]
# This changes the symbol to indicate a mutable commit that's an ancestor of a
# bookmark. This is useful to see which commits might be pushed with jj git
# push.
log_node = '''
if(self && !current_working_copy && !immutable && !conflict && in_branch(self),
  "◇",
  builtin_log_node
)
'''
